# ad_traffic_generator.py

"""
Module: ad_traffic_generator
Description:
    This script generates synthetic ad-tech traffic data (clicks and views)
    and streams it to a Kafka topic.

    Key Features:
    - Weighted Country Distribution: Simulates realistic market shares (US dominant)
      with specific inclusion of Palestine (PS).
    - Bot Simulation: Generates traffic from a small pool of repeating IPs to
      simulate bot farms.
    - Data Corruption: Intentionally introduces data quality issues (missing fields,
      invalid timestamps) to test downstream data cleaning pipelines.
    - Rate Limiting: Controls the flow of events per second via CLI arguments.

Dependencies:
    - kafka-python: For producing messages to Kafka.
    - faker: For generating realistic dummy data (IPs, etc.).
"""

# Import the KafkaProducer to allow publishing messages to a Kafka broker
from kafka import KafkaProducer
# Import Faker to generate fake data (IP addresses, user agents, etc.)
from faker import Faker
# Import json for serializing dictionary objects into JSON strings
import json
# Import time for sleep functions (rate limiting) and current time tracking
import time
# Import random for probability logic (bot detection, country selection)
import random
# Import datetime classes for timestamp generation
from datetime import datetime, timedelta, timezone
# Import uuid for generating unique event identifiers
import uuid
# Import argparse to handle command-line arguments (e.g., events per second)
import argparse

# Initialize the Faker generator object
fake = Faker()

# ----------------------------------------------------------------------
# Configuration (defaults – can be overridden via CLI)
# ----------------------------------------------------------------------
# The address of the Kafka Broker (Server:Port)
KAFKA_BROKER = "localhost:9092"
# The specific Kafka topic name where events will be published
KAFKA_TOPIC = "ad_stream"
# Default rate of event generation if not specified in CLI arguments
EVENTS_PER_SECOND_DEFAULT = 50

# Weighted Country Distribution (Realistic Ad Market + Palestine)
# Using a list with repetitions to create a weighted random selection.
# This acts as a Probability Mass Function (PMF).
COUNTRIES = (
        ["US"] * 35 +  # USA: 35% (dominant ad market)
        ["CN"] * 12 +  # China: 12%
        ["UK"] * 9 +  # United Kingdom: 9%
        ["DE"] * 7 +  # Germany: 7%
        ["PS"] * 6 +  # Palestine: 6%
        ["FR"] * 5 +  # France: 5%
        ["JP"] * 5 +  # Japan: 5%
        ["CA"] * 4 +  # Canada: 4%
        ["AU"] * 3 +  # Australia: 3%
        ["BR"] * 3 +  # Brazil: 3%
        ["IN"] * 3 +  # India: 3%
        ["KR"] * 2 +  # South Korea: 2%
        ["MX"] * 2 +  # Mexico: 2%
        ["ES"] * 2 +  # Spain: 2%
        ["IT"] * 2  # Italy: 2%
    # Total: 100 entries = 100% probability distribution
)

# BOT SIMULATION: Small pool of IPs that will repeat
# A small pool simulates a "bot farm" reusing IPs heavily.
BOT_IP_POOL = [fake.ipv4() for _ in range(20)]  # Generate 20 static IPs for bots

# LEGITIMATE USER POOL: Moderate pool of real user IPs
# A larger pool simulates returning users.
LEGITIMATE_IP_POOL = [fake.ipv4() for _ in range(200)]  # Generate 200 static IPs for real users


def generate_ad_event():
    """
    Generate a single synthetic ad event with realistic bot/user distribution.

    Logic:
        1. Determines if the actor is a 'bot' (30% chance) or 'user' (70% chance).
        2. Selects an IP address based on actor type (bots reuse IPs heavily).
        3. Constructs the event payload with a specific timestamp (UTC+2).
        4. Injects random data corruption (5% chance) to test data quality pipelines.

    Returns:
        dict: A dictionary representing the ad event (click or view).
    """
    # Determine if this event is from a bot or legitimate user based on probability
    is_bot = random.random() < 0.30  # 30% chance the event is generated by a bot

    if is_bot:
        # Bots: High repeat rate from the small IP pool defined above
        ip_address = random.choice(BOT_IP_POOL)
        # Bots are programmed to click more often; 95% click rate, 5% view rate
        action = "click" if random.random() < 0.95 else "view"
    else:
        # Legitimate Users: Mix of repeat users and completely new IPs
        if random.random() < 0.70:  # 70% chance it's a returning user (from pool)
            ip_address = random.choice(LEGITIMATE_IP_POOL)
        else:  # 30% chance it's a completely new user (generate new IP)
            ip_address = fake.ipv4()
        # Real users have a random distribution of actions
        action = random.choice(["click", "view"])

    # Construct the event dictionary
    event = {
        # Timestamp generation:
        # 1. Get current time.
        # 2. Apply timezone offset: UTC + 2 hours (Simulating Gaza/Hebron time).
        # 3. Format as string matching Spark's standard format.
        # 4. Slice [:-3] to trim microseconds to milliseconds for cleaner logging.
        "timestamp": datetime.now(timezone(timedelta(hours=2))).strftime("%Y-%m-%d %H:%M:%S.%f")[:-3],

        # Generate a unique UUID for this specific event
        "event_id": str(uuid.uuid4()),

        # Assign the selected IP address
        "ip_address": ip_address,

        # Select country using the weighted distribution list defined globally
        "country": random.choice(COUNTRIES),

        # Assign the action (click/view)
        "action": action,

        # Assign a random campaign ID (1 through 10)
        "campaign_id": f"campaign_{random.randint(1, 10)}",

        # Randomly assign a device type
        "device": random.choice(["mobile", "desktop", "tablet"]),
    }

    # Inject realistic data quality issues (5% probability)
    # This helps test error handling in consumers (e.g., Spark/Flink)
    if random.random() < 0.05:  # 5% chance of malformed data
        # Randomly select a type of corruption
        corruption_type = random.choice([
            "missing_ip",
            "invalid_timestamp",
            "missing_campaign",
            "corrupted_country"
        ])

        # Apply the selected corruption
        if corruption_type == "missing_ip":
            event["ip_address"] = None  # Simulate NULL IP
        elif corruption_type == "invalid_timestamp":
            event["timestamp"] = "INVALID_TIMESTAMP"  # Simulate parse error string
        elif corruption_type == "missing_campaign":
            event["campaign_id"] = None  # Simulate NULL campaign
        elif corruption_type == "corrupted_country":
            event["country"] = "XXXX"  # Simulate Invalid country code length

    # Return the constructed (and potentially corrupted) event dictionary
    return event


def parse_args():
    """
    Parse command-line arguments to allow runtime configuration.

    Supported Arguments:
        --eps (int): Events Per Second. Defaults to 50.

    Returns:
        argparse.Namespace: Object containing the parsed arguments.
    """
    # Create the parser object with a description
    parser = argparse.ArgumentParser(
        description="Synthetic Ad-Tech traffic generator for Kafka (with weighted countries)"
    )
    # Add the 'eps' argument for rate limiting
    parser.add_argument(
        "--eps",
        type=int,
        default=EVENTS_PER_SECOND_DEFAULT,
        help="Events per second (default: 50)",
    )
    # Parse and return arguments
    return parser.parse_args()


def main():
    """
    Main execution entry point.
    1. Sets up Kafka Producer.
    2. Prints configuration details.
    3. Enters an infinite loop to generate and stream data.
    4. Handles graceful shutdown on KeyboardInterrupt.
    """
    # Parse CLI arguments
    args = parse_args()
    # Ensure events per second is at least 1 to avoid division by zero errors later
    events_per_second = max(1, args.eps)

    # Initialize Kafka Producer
    producer = KafkaProducer(
        bootstrap_servers=[KAFKA_BROKER],  # Connection string
        value_serializer=lambda v: json.dumps(v).encode("utf-8"),  # Auto-serialize dicts to JSON bytes
        compression_type="gzip",  # Compress messages for network efficiency
        linger_ms=10,  # Wait up to 10ms to batch messages (improves throughput)
        batch_size=16384,  # Maximum size of a batch in bytes
    )

    # Generate a sample event to display the schema to the user on startup
    sample_event = generate_ad_event()

    # Print the startup banner and configuration details
    print("=" * 70)
    print("Ad Traffic Generator - WEIGHTED COUNTRY DISTRIBUTION")
    print("=" * 70)
    print("Sample event schema:")
    print(json.dumps(sample_event, indent=2))  # Pretty print the sample JSON
    print("\n" + "=" * 70)

    # Visual representation of the country distribution
    print("Country Distribution:")
    print("  US (USA):        35%  ████████████████████████")
    print("  CN (China):      12%  ████████")
    print("  UK (Britain):     9%  ██████")
    print("  DE (Germany):     7%  █████")
    print("  PS (Palestine):   6%  ████ ")
    print("  FR (France):      5%  ███")
    print("  JP (Japan):       5%  ███")
    print("  CA (Canada):      4%  ███")
    print("  Others:          17%  ███████████")
    print("=" * 70)

    # Print runtime statistics
    print(f"Target Rate: {events_per_second} events/second")
    print(f"Bot IP Pool Size: {len(BOT_IP_POOL)}")
    print(f"Legitimate IP Pool Size: {len(LEGITIMATE_IP_POOL)}")
    print(f"Publishing to Kafka Topic: {KAFKA_TOPIC}")
    print("-" * 70)

    # Initialize counters for progress tracking
    event_count = 0
    start_time = time.time()

    try:
        # Infinite loop to stream data until stopped
        while True:
            # Generate a single synthetic event
            event = generate_ad_event()

            # Send the event to the Kafka topic
            # Note: This is asynchronous; it returns a Future but we don't block on it here
            producer.send(KAFKA_TOPIC, value=event)

            # Increment the total counter
            event_count += 1

            # Rate limiting logic:
            # Sleep for 1/rate seconds to maintain the desired EPS (Events Per Second)
            time.sleep(1.0 / events_per_second)

            # Progress reporting: Print stats every 5 seconds worth of events
            if event_count % (events_per_second * 5) == 0:
                elapsed = time.time() - start_time
                actual_rate = event_count / elapsed
                print(
                    f"Sent {event_count} events | "
                    f"Rate: {actual_rate:.1f} events/sec"
                )

    except KeyboardInterrupt:
        # Handle User interruption (Ctrl+C) gracefully
        print("\nShutting down generator (KeyboardInterrupt)...")

    finally:
        # Ensure producer is always flushed (buffers emptied) and closed
        producer.flush()
        producer.close()
        print(f"Total events generated: {event_count}")


# Standard Python boilerplate to call main() only if executed as a script
if __name__ == "__main__":
    main()